apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: todo-migrate
    app.openshift.io/vcs-uri: https://github.com/luizerico/DO288-apps.git
    deployment.kubernetes.io/revision: "1"
    jkube.io/git-branch: todo-migrate
    jkube.io/git-commit: f355431fb67e02bf81041c1ddf395770a774c657
    jkube.io/git-url: https://github.com/luizerico/DO288-apps.git
  generation: 1
  labels:
    app: todo-api
    group: com.redhat.training.openshift.todoapi
    provider: jkube
    version: 1.0.0-SNAPSHOT
  name: todo-api
  namespace: cytgep-todo-migrate
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-api
      group: com.redhat.training.openshift.todoapi
      provider: jkube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-api
        group: com.redhat.training.openshift.todoapi
        provider: jkube
        version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: image-registry.openshift-image-registry.svc:5000/cytgep-todo-migrate/todo-api@sha256:b2e320dbc7ee106a07157cfdff725f27f8a7a3ee98ddfda4aaec6c3cbd3b1359
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
